print ('Hello and welcome to Informassure Inc.')
print ('What is your name?')
myName = input()
print ('It is nice to meet you, '  +myName)
print ('How old are you?')
myAge = input()
print ('------end of line------')
print ('Please, add two numbers')
num1 = input("Type your first number ")
num2 = input("Type the second number to add ")
sum = int(num1) + int(num2)
print ("Thank you! The summation is", sum)

#num1 = input("Type your first number ")
#num2 = input("Type your second number you want to add ")
#sum = int(num1) + int(num2)
#print ("The summation is equals to", sum)